### ISSUE TITLE
(op*) gives a lexical error

### ISSUE THREAD

**Issue by Munksgaard** [kfl/mosml#18]
Trying to compile the following file:

test.sml:

    val _ = print (Int.toString (foldl (op*) 1 [2,4,5]))

gives me:

    $ mosmlc test.sml
    File "test.sml", line 1, characters 38-40:
    ! val _ = print (Int.toString (foldl (op*) 1 [2,4,5]))
    !                                       ^^
    ! Lexical error: unmatched comment bracket.

If I insert a space after the asterix, MosML will compile the file as well.

I understand that there's som ambiguity here, since `*)` looks an awful lot like the end of a comment, but I can see that mlton compiles the same file without any troubles.

Is this the desired behavior for MosML?

**Comment by Munksgaard** [comment]
I also see that SML/NJ gives a syntax error as well. Perhaps we should just leave it as it is?

**Comment by kfl** [comment]
Yes, this is actually the intended behaviour.
