### ISSUE TITLE
PackRealLittle

### ISSUE THREAD

**Issue by athas** [kfl/mosml#63]
It would be nice to have PackRealLittle as documented here: https://smlfamily.github.io/Basis/pack-float.html

Probably needs #62 to be implemented first.

PackReal32Little and PackReal64Little would also be useful, except that MosML does not have Real32.

**Comment by kfl** [comment]
Moscow ML almost have the functionality that you are asking for in the [`Mosml` module](https://mosml.org/mosmllib/Mosml.html). For example, the [`Mosml.doubleVec` function](https://mosml.org/mosmllib/Mosml.html#doubleVec-val) converts a `real` to an eight-element vector of `Word8.word` but in big-endian.
